version: '3.3'

services:
  db:
    image: "postgres:14-alpine"
    container_name: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=prodigy
      - POSTGRES_DB=keycloak
    ports:
      - "5433:5432"
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: "keycloak"
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=prodigy
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=172.105.75.119
      - KC_HTTPS_PORT=8443
      - KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/conf/server.crt
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/conf/server.key
      - KC_HTTP_ENABLED=true
      - KC_SPI_ALLOWED_ORIGINS=http://172.105.75.119:3001
    volumes:
      - ~/kloack/certs/server.crt:/opt/keycloak/conf/server.crt:ro
      - ~/kloack/certs/server.key:/opt/keycloak/conf/server.key:ro
    user: root
    command:
      - start-dev
    ports:
      - "8443:8443"
    depends_on:
      - db
    restart: always  
      
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: "backend"
    command: >
      sh -c "python run.py migrate &&
      python run.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=prodigy
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - KEYCLOAK_URL=https://172.105.75.119:8443/auth
      - KEYCLOAK_REALM=kloack
      - KEYCLOAK_CLIENT_ID=backend-service
      - KEYCLOAK_CLIENT_SECRET=tBTmjljgnIGseGH2zJUhZMJMTZ7AY4Kb
    depends_on:
      - db
      - keycloak
    restart: always

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: "client"
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://172.105.75.119:8000/api
      - REACT_APP_KEYCLOAK_URL=https://172.105.75.119:8443/auth
      - REACT_APP_KEYCLOAK_REALM=kloack
      - REACT_APP_KEYCLOAK_CLIENT_ID=backend-service
    depends_on:
      - backend
      - keycloak
    restart: always
    command: sh -c "npm install && npm start"

volumes:
  postgres_data:
